config/routes.rb
Rails.application.routes.draw do
  resources :mycontacts
  get 'messages/index'
  get 'messages', to: 'messages#index'

  get 'messages/add'
  post 'messages/add', to: 'messages#create'

  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'

  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'

  get 'cards/index'
  get 'cards', to: 'cards#index'

  get 'cards/add'
  post 'cards/add'

  get 'cards/:id', to: 'cards#show'

  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'

  get 'cards/delete/:id', to: 'cards#delete'

  get 'people/index'
  get 'people', to: 'people#index'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people/find'
  post 'people/find'
  get 'people/:id', to: 'people#show'
  get 'people/edit/:id', to: 'people#edit'
  patch 'people/edit/:id', to: 'people#update'
  get 'people/delete/:id', to: 'people#delete'

  get 'msgboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index'
  get 'hello', to: 'hello#index'
  post 'hello', to: 'hello#index'
  post 'hello/index'
  get 'hello/other'

  get 'msgboard', to: 'msgboard#index'
  post 'msgboard', to: 'msgboard#index'
  get 'msgboard/index'
  post 'msgboard/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :person

  validates :message, presence: {message:'を書いてください。'}
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
  validates :name, presence: {message: 'は、必須項目です。'}
  validates :age, numericality: {message: 'は、数字で入力ください。'}
  validates :nationality, inclusion: {in: [true, false],
                                      message: 'は、真偽値です。'}
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :message

  validates :name, presence: {message: 'は、必須項目です。'}
  validates :age, numericality: {message: 'は、数字で入力してください。'}
  validates :mail, email: {message:'はメールアドレスではありません。'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  layout 'cards'

  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def add
    if request.post? then
      Card.create(card_params)
      goback
    else
      @card = Card.new
    end
  end

  def edit
    @card = Card.find(params[:id])
    if request.patch? then
      @card.update(card_params)
      goback
    end
  end

  def delete
    Card.find(params[:id]).destroy
    goback
  end

  private

  def card_params
    params.require(:card).permit(:title, :author, :price,
                                 :publisher, :memo)
  end

  def goback
    redirect_to '/cards'
  end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout 'hello'

  def index
    @header = 'layout sample'
    @footer = 'copyright SYODA=Tuyano 2020.'
    @title = 'New Layout'
    @msg = 'this is sample page!'
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout 'messages'

  def index
    @msg = 'Message data.'
    @data = Message.all
  end

  def show
    @msg = "Indexed data."
    @message = Message.find(params[:id])
  end

  def add
    @msg = 'Message data.'
    @message = Message.new
  end

  def create
    @message = Message.new message_params
    if @message.save then
      redirect_to '/messages'
    else
      render 'add'
    end
  end

  def edit
    @msg = "edit data.[id = " + params[:id] + "]"
    @message = Message.find(params[:id])
  end

  def update
    obj = Message.find(params[:id])
    obj.update(message_params)
    redirect_to '/messages'
  end

  def delete
    obj = Message.find(params[:id])
    obj.destroy
    redirect_to '/messages'
  end

  private
  def message_params
    params.require(:message).permit(:person_id, :title, :message)
  end

  
end

app/controllers/msgboard_controller.rb
class MsgboardController < ApplicationController
  layout 'msgboard'

  def initialize
    super
    begin
      @msg_data = JSON.parse(File.read('data.txt'))
    rescue
      @msg_data = Hash.new
    end
    @msg_data.each do |key, obj|
      if Time.now.to_i - key.to_i > 24 * 60 * 60 then
        @msg_data.delete(key)
      end
    end
    File.write("data.txt", @msg_data.to_json)
  end

  def index
    if request.post? then
      # フォームに入力した情報をJSON形式に変換してファイルに書き込む
      obj = MyData.new(msg: params['msg'], name:params['name'],
        mail: params['mail'])
      @msg_data[Time.now.to_i] = obj
      data = @msg_data.to_json
      File.write("data.txt", data)
      @msg_data = JSON.parse(data)
    end
  end
end

class MyData
  attr_accessor :name
  attr_accessor :mail
  attr_accessor :msg

  def initialize msg:msg, name:name, mail:mail
    self.name = name
    self.mail = mail
    self.msg = msg
  end
end

app/controllers/mycontacts_controller.rb
class MycontactsController < ApplicationController
  before_action :set_mycontact, only: [:show, :edit, :update, :destroy]

  # GET /mycontacts
  # GET /mycontacts.json
  def index
    @mycontacts = Mycontact.all
  end

  # GET /mycontacts/1
  # GET /mycontacts/1.json
  def show
  end

  # GET /mycontacts/new
  def new
    @mycontact = Mycontact.new
  end

  # GET /mycontacts/1/edit
  def edit
  end

  # POST /mycontacts
  # POST /mycontacts.json
  def create
    @mycontact = Mycontact.new(mycontact_params)

    respond_to do |format|
      if @mycontact.save
        format.html { redirect_to @mycontact, notice: 'Mycontact was successfully created.' }
        format.json { render :show, status: :created, location: @mycontact }
      else
        format.html { render :new }
        format.json { render json: @mycontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mycontacts/1
  # PATCH/PUT /mycontacts/1.json
  def update
    respond_to do |format|
      if @mycontact.update(mycontact_params)
        format.html { redirect_to @mycontact, notice: 'Mycontact was successfully updated.' }
        format.json { render :show, status: :ok, location: @mycontact }
      else
        format.html { render :edit }
        format.json { render json: @mycontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mycontacts/1
  # DELETE /mycontacts/1.json
  def destroy
    @mycontact.destroy
    respond_to do |format|
      format.html { redirect_to mycontacts_url, notice: 'Mycontact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mycontact
      @mycontact = Mycontact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mycontact_params
      params.require(:mycontact).permit(:name, :age, :nationality, :mail)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  layout 'people'

  def index
    @msg = 'Person data.'
    @data = Person.all
  end

  def show
    @msg = 'Indexed data.'
    @data = Person.find(params[:id])
  end

  def add
    @msg = "add new data."
    @person = Person.new
  end

  def create
    @person = Person.new person_params
    if @person.save then
      redirect_to '/people'
    else
      render 'add'
    end
  end

  def edit
    @msg = "edit data.[id = " + params[:id] + "]"
    @person = Person.find(params[:id])
  end

  def update
    obj = Person.find(params[:id])
    obj.update(person_params)
    redirect_to '/people'
  end

  def delete
    obj = Person.find(params[:id])
    obj.destroy
    redirect_to '/people'
  end

  def find
    @msg = 'please type search word...'
    if request.post? then
      f = params[:find].split(',')
      @people = Person.all.limit(f[0]).offset(f[1])
    else
      @people = Person.all
    end
  end


  private

  def person_params
    params.require(:person).permit(:name, :age, :mail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/msgboard_helper.rb
module MsgboardHelper
end

app/helpers/mycontacts_helper.rb
module MycontactsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/cards/add.html.erb
<h1 class="display-4 text-primary">Cards#add</h1>
<p>※登録する読書データを入力してください。</p>
<%= form_for(@card, url: {controller: 'cards',
                          action: 'add'}) do |form| %>
  <div class="form-group">
    <label for="title">タイトル</label>
    <%= form.text_field :title, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label for="author">著者</label>
    <%= form.text_field :author, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label for="price">価格</label>
    <%= form.text_field :price, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label for="publisher">出版社</label>
    <%= form.text_field :publisher, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label for="memo">コメント</label>
    <%= form.text_area :memo, {rows: 5, class: "form-control"} %>
  </div>
  <%= form.submit "保存" %>
<% end %>
<p class="link"><a href="/cards">
  &lt;&lt; ※トップページに戻る
</a></p>

app/views/cards/edit.html.erb
<h1 class="display-4 text-primary">Cards#edit</h1>
<p>※「<%= @card.title %>」の内容を編集します。</p>
<%= form_for(@card, url: {controller: 'cards',
                          action: 'edit', id: @card.id}) do |form| %>
  <div class="form-group">
    <label for="title">タイトル</label>
    <%= form.text_field :title, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label for="author">著者</label>
    <%= form.text_field :author, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label for="price">価格</label>
    <%= form.text_field :price, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label for="publisher">出版社</label>
    <%= form.text_field :publisher, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label for="memo">コメント</label>
    <%= form.text_area :memo, {rows: 5, class: "form-control"} %>
  </div>
  <%= form.submit "更新" %>
<% end %>
<p class="link"><a href="/cards">&lt;&lt; ※トップページに戻る</a></p>

app/views/cards/index.html.erb
<h1 class="display-4 text-primary">Cards#index</h1>
<p>※現在、登録されているデータの一覧です。</p>
<table class="table">
  <tr>
    <th>ID</th>
    <th>題名</th>
    <th>著者</th>
    <th colspan="2"></th>
  </tr>
  <% @cards.each do |obj| %>
    <tr>
      <td width="35px"><%= obj.id %></td>
      <td width="50%"><a href="/cards/<%= obj.id %>">
        <%= obj.title %>
      </a></td>
      <td><%= obj.author %></td>
      <td width="80px">
        <a href="/cards/edit/<%= obj.id %>">
          編集
        </a>
      </td>
      <td width="80px">
        <a href="javascript:delData(
          <%= (obj.id.to_s + ",'".to_s +
            obj.title.to_s).html_safe %>'
        );">削除</a>
      </td>
    </tr>
  <% end %>
</table>
<p>
  <a href="/cards/add">
    ※新しいデータを入力 &gt;&gt;
  </a>
</p>
<script>
    function delData(id, title) {
        if (confirm('「' + title + '」のデータを削除しますか？')) {
            document.location = "/cards/delete/" + id;
        }
    }
</script>

app/views/cards/show.html.erb
<h1 class="display-4 text-primary">Cards#show</h1>
<p>※「<%= @card.title %>」の読書データ</p>
<table class="table">
  <tr>
    <th width="200">Id</th>
    <td><%= @card.id %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @card.title %></td>
  </tr>
  <tr>
    <th>著者</th>
    <td><%= @card.author %></td>
  </tr>
  <tr>
    <th>価格</th>
    <td><%= @card.price %></td>
  </tr>
  <tr>
    <th>出版社</th>
    <td><%= @card.publisher %></td>
  </tr>
  <tr>
    <th>コメント</th>
    <td><%= @card.memo %></td>
  </tr>
</table>
<p><a href="/cards">&lt;&lt;※トップページに戻る</a></p>

app/views/hello/index.html.erb
<p><%= @msg %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/layouts/cards.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cards</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
  <style>
      h1 {
          margin: 25px 0px;
      }

      p {
          margin: 25px 0px;
      }
  </style>
</head>
<body class="container">
<%= yield %>
</body>
</html>

app/views/layouts/hello.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <%= stylesheet_link_tag 'application',
    media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="container text-body">
    <%= render template:'layouts/hello_header' %>
    <%= yield %>
    <%= render template:'layouts/hello_footer' %>
</body>

</html>

app/views/layouts/hello_footer.html.erb
<div class="mt-5 text-right small text-dark border-bottom border-dark">
    <%= @footer %>
</div>

app/views/layouts/hello_header.html.erb
<h1 class="display-4 text-center mt-1 mb-4 text-primary">
    <%= @header %>
</h1>

app/views/layouts/messages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
  <%= stylesheet_link_tag 'messages',
                          'data-turbolinks-track': 'reload' %>
</head>

<body class="container">
<%= yield %>
</body>
</html>

app/views/layouts/msgboard.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
</head>

<body class="container text-body">
    <h1 class="mb-4 display-4 text-primary">MsgBoard</h1>
    <%= yield %>
    <div class="mt-4 text-center small text-dark border-top border-dark">
        copyright SYODA-Tuyano. 2020
      </div>
</body>

</html>

app/views/layouts/people.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
</head>
<%= stylesheet_link_tag 'people', media: 'all' %>
<body class="container">
<%= yield %>
</body>
</html>

app/views/messages/add.html.erb
<h1 class="display-4 text-primary">
  Messages#add</h1>
<p><%= @msg %></p>
<% if @message.errors.any? %>
  <ul>
    <% @message.errors.full_messages.each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
<% end %>
<table>
  <%= form_for(@message, url: {controller: 'messages', action: 'create'}) do |form| %>
    <td>
      <div class="form-group">
        <label for="person_id">person ID</label>
        <%= form.text_field :person_id, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <label for="title">title</label>
        <%= form.text_field :title, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <label for="message">message</label>
        <%= form.text_area :message, {rows: 3, class: "form-control"} %>
      </div>
      <%= form.submit "作成" %></td>
  <% end %>
</table>

app/views/messages/edit.html.erb
<h1 class="display-4 text-primary">
  Messages#edit
</h1>
<p><%= @msg %></p>
<% if @message.errors.any? %>
  <ul>
    <% @message.errors.full_messages.each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
<% end %>
<table>
  <%= form_for(@message, url: {controller: 'messages', action: 'update'}) do |form| %>
    <div class="form-group">
      <label for="person_id">person ID</label>
      <%= form.text_field :person_id, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label for="title">title</label>
      <%= form.text_field :title, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <label for="message">message</label>
      <%= form.text_area :message, {rows:3, class:"form-control"} %>
    </div>
    <%= form.submit "更新" %>
  <% end %>
</table>

app/views/messages/index.html.erb
<h1 class="display-4 text-primary">
  Messages#index
</h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>Id</th>
    <th>title</th>
    <th>person</th>
    <th colspan="2"></th>
  </tr>
  <% @data.each do |obj| %>
    <tr>
      <td><%= obj.id %></td>
      <td><a href="/messages/<%= obj.id %>"><%= obj.title %></a></td>
      <td><%= obj.person.name %></td>
      <td><a href="/messages/edit/<%= obj.id %>">Edit</a></td>
      <td><a href="javascript:delData(<%= obj.id %>);">Delete</a></td>
    </tr>
  <% end %>
</table>
<script>
    function delData(num) {
        if (confirm('このデータを削除しますか？')) {
            document.location = "/messages/delete/" + num;
        }
        return false;
    }
</script>

app/views/messages/show.html.erb
<h1 class="display-4 text-primary">
  Messages#show</h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>Id</th>
    <td><%= @message.id %></td>
  </tr>
  <tr>
    <th>Person</th>
    <td><%= @message.person_id %></td>
  </tr>
  <tr>
    <th>title</th>
    <td><%= @message.title %></td>
  </tr>
  <tr>
    <th>message</th>
    <td><%= @message.message %></td>
  </tr>
  <tr>
    <th>created</th>
    <td><%= @message.created_at %></td>
  </tr>
</table>

app/views/msgboard/index.html.erb
<%= form_tag(controller: "msgboard", action: "index") do %>
<div class="form-group">
    <label for="name">名前</label>
    <%= text_field_tag("name", "", {class:"form-control"}) %>
</div>
<div class="form-group">
    <label for="name">メール</label>
    <%= text_field_tag("mail", "", {class:"form-control"}) %>
</div>
<div class="form-group">
    <label for="name">メッセージ</label>
    <%= text_area_tag("msg", "", {class:"form-control"}) %>
</div>
<%= submit_tag("Click", {class:"btn btn-primary"}) %>
<% end %>

<table class="table mt-4">
    <tr>
        <th style="width:50%">メッセージ</th>
        <th>名前</th>
        <th>メール</th>
        <th>投稿日時</th>
    </tr>
    <% @msg_data.each do |key, obj| %>
    <tr>
        <td class="msg"><%= obj['msg'] %></td>
        <td class="name"><%= obj['name'] %></td>
        <td class="mail"><%= obj['mail'] %></td>
        <td class="time"><%= Time.at(key.to_i) %></td>
    </tr>
    <% end %>
</table>

app/views/mycontacts/_form.html.erb
<%= form_with(model: mycontact, local: true) do |form| %>
  <% if mycontact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mycontact.errors.count, "error") %> prohibited this mycontact from being saved:</h2>

      <ul>
        <% mycontact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.check_box :nationality %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_area :mail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mycontacts/edit.html.erb
<h1>Editing Mycontact</h1>

<%= render 'form', mycontact: @mycontact %>

<%= link_to 'Show', @mycontact %> |
<%= link_to 'Back', mycontacts_path %>

app/views/mycontacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mycontacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mycontacts.each do |mycontact| %>
      <tr>
        <td><%= mycontact.name %></td>
        <td><%= mycontact.age %></td>
        <td><%= mycontact.nationality %></td>
        <td><%= mycontact.mail %></td>
        <td><%= link_to 'Show', mycontact %></td>
        <td><%= link_to 'Edit', edit_mycontact_path(mycontact) %></td>
        <td><%= link_to 'Destroy', mycontact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mycontact', new_mycontact_path %>

app/views/mycontacts/new.html.erb
<h1>New Mycontact</h1>

<%= render 'form', mycontact: @mycontact %>

<%= link_to 'Back', mycontacts_path %>

app/views/mycontacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mycontact.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @mycontact.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @mycontact.nationality %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @mycontact.mail %>
</p>

<%= link_to 'Edit', edit_mycontact_path(@mycontact) %> |
<%= link_to 'Back', mycontacts_path %>

app/views/people/add.html.erb
<h1 class="display-4 text-primary">People#add</h1>
<p>
  <%= @msg %></p>
<% if @person.errors.any? %>
  <ul>
    <% @person.errors.full_messages.each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for(@person, url: {controller: 'people', action: 'create'}) do |form| %>
  <div class="form-group">
    <label for="name">Name</label>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="age">Age</label>
    <%= form.text_field :age, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="mail">Mail</label>
    <%= form.text_field :mail, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/people/edit.html.erb
<h1 class="display-4 text-primary">People#edit</h1>
<p><%= @msg %></p>
<%= form_for(@person, url: {controller: 'people',
                            action: 'update', id: @person.id}) do |form| %>
  <div class="form-group">
    <label for="name">Name</label>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="age">Age</label>
    <%= form.text_field :age, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="mail">Mail</label>
    <%= form.text_field :mail, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/people/find.html.erb
<h1 class="display-4 text-primary">
  People#Find
</h1>
<p><%= @msg %></p>
<%= form_tag(controller: "people", action: "find") do %>
  <div class="form-group">
    <label for="find">Find</label>
    <%= text_field_tag("find", '', {class: "form-control"}) %>
  </div>
  <%= submit_tag("Click") %>
<% end %>

<table class="table">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Age</th>
    <th>Mail</th>
  </tr>
  <% @people.each do |obj| %>
    <tr>
      <td><%= obj.id %></td>
      <td><%= obj.name %></td>
      <td><%= obj.age %></td>
      <td><%= obj.mail %></td>
    </tr>
  <% end %>
</table>

app/views/people/index.html.erb
<h1 class="display-4 text-primary">People#index</h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>Id</th>
    <th>Name</th>
  </tr>
  <% @data.each do |obj| %>
    <tr>
      <td><%= obj.id %></td>
      <td><a href="/people/<%= obj.id %>>">
        <%= obj.name %></a></td>
      <td><a href="/people/edit/<%= obj.id %>">Edit</a>&nbsp;&nbsp;
        <a href="javascript:delData(<%= obj.id %>);">
          Delete
        </a>
      </td>
    </tr>
  <% end %>
</table>
<script>
    function delData(num) {
        if (confirm('このデータを削除しますか？')) {
            document.location = "/people/delete/" + num;
        }
        return false;
    }
</script>

app/views/people/show.html.erb
<h1 class="display-4 text-primary">People#show</h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>Id</th>
    <td><%= @data.id %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= @data.name %></td>
  </tr>
  <tr>
    <th>Age</th>
    <td><%= @data.age %></td>
  </tr>
  <tr>
    <th>Mail</th>
    <td><%= @data.mail %></td>
  </tr>
  <tr>
    <th>Message</th>
    <td>
      <% if @data.message != nil then %>
        <% @data.message.each do |obj| %>
          <%= '「' + obj.title + '」' %>
        <% end %>
      <% end %></td>
  </tr>
</table>